package generator

import (
	"fmt"
	"strings"

	"deployable/internal/analyzer"
)

// GenerateDeploymentGuide returns a DEPLOYMENT.md summarizing what to fix
// first and how to deploy, using the same semantic analysis the report page
// shows.
func GenerateDeploymentGuide(result *analyzer.Result) string {
	var b strings.Builder
	b.WriteString("# Deployment Guide\n\n")
	b.WriteString("Generated by Deployable — review before using in production.\n\n")

	stack := result.StackInfo.Language
	if result.StackInfo.Framework != "" {
		stack += " (" + result.StackInfo.Framework + ")"
	}
	b.WriteString("**Stack:** " + stack + "\n\n")

	if result.Semantic != nil && len(result.Semantic.CriticalGaps) > 0 {
		b.WriteString("## Fix before deploying\n\n")
		for _, gap := range result.Semantic.CriticalGaps {
			b.WriteString("- [ ] " + gap + "\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Files in this bundle\n\n")
	b.WriteString("- `Dockerfile` — multi-stage build\n")
	b.WriteString("- `docker-compose.yml` — app plus any detected databases\n")
	b.WriteString("- `.env.example` — environment variables this project reads\n")
	b.WriteString("- `.github/workflows/ci.yml` — build/test on push\n\n")

	if result.Semantic != nil && len(result.Semantic.Platforms) > 0 {
		top := result.Semantic.Platforms[0]
		b.WriteString(fmt.Sprintf("## Deploying to %s\n\n", top.Name))
		if top.Reasoning != "" {
			b.WriteString(top.Reasoning + "\n\n")
		}
		for i, step := range top.DeploySteps {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, step))
		}
		if len(top.DeploySteps) > 0 {
			b.WriteString("\n")
		}
	}

	return b.String()
}
