package generator

import (
	"sort"
	"strings"

	"deployable/internal/analyzer"
)

var envVarDescriptions = map[string]string{
	"DATABASE_URL": "Database connection string, e.g. postgres://user:pass@host:5432/db",
	"POSTGRES_URL": "Postgres connection string",
	"REDIS_URL":    "Redis connection string, e.g. redis://localhost:6379/0",
	"MONGO_URL":    "MongoDB connection string",
	"MONGODB_URI":  "MongoDB connection string",
	"PORT":         "HTTP port to listen on",
	"SECRET_KEY":   "Random secret for sessions/cookies. Generate: openssl rand -hex 32",
	"JWT_SECRET":   "JWT signing secret. Generate: openssl rand -hex 32",
	"API_KEY":      "API key for an external service",
	"NODE_ENV":     "development | production",
	"APP_ENV":      "development | production",
	"SMTP_HOST":    "SMTP server host for outgoing email",
	"SMTP_PORT":    "SMTP server port",
	"SMTP_USER":    "SMTP username",
	"SMTP_PASS":    "SMTP password",
}

// GenerateEnvExample returns a .env.example listing every env var referenced
// in the source, annotated with a description where the name is recognized.
func GenerateEnvExample(result *analyzer.Result) string {
	vars := append([]string{}, result.EnvVars...)
	sort.Strings(vars)

	var b strings.Builder
	b.WriteString("# Generated by Deployable — fill in real values before deploying.\n\n")

	if len(vars) == 0 {
		b.WriteString("# No environment variables were detected in this project.\n")
		return b.String()
	}

	for _, v := range vars {
		if desc, ok := envVarDescriptions[v]; ok {
			b.WriteString("# " + desc + "\n")
		}
		b.WriteString(v + "=\n")
	}
	return b.String()
}
